name: CI/CD Workflow with Self-Hosted Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # Use the self-hosted runner instead of GitHub-hosted runner
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Angular project
      - name: Build project
        run: npm run build --if-present

      # Step 5: Run tests
      - name: Run tests
        run: npm run test -- --watch=false

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to server
        run: |
          # Add deployment commands specific to your environment
          echo "Deploying application..."
