name: CI/CD Workflow with GitHub-hosted Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Step 5: Build the Angular application
      - name: Build Angular application
        run: ng build 

      # Step 6: Run tests (optional, uncomment if needed)
      # - name: Run tests
      #   run: npm run test -- --watch=false

  # Optionally add a deploy step
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to server
  #       run: |
  #         # Add deployment commands specific to your environment
  #         echo "Deploying application..."
