name: CI/CD Workflow with GitHub-hosted Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Step 5: Build the Angular application
      - name: Build Angular application
        run: ng build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH
      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Transfer build artifacts to the shared server
      - name: Deploy to shared server
        run: |
          ssh user@shared-server "mkdir -p /var/www/my-angular-app"
          scp -r dist/my-angular-app/* user@shared-server:/var/www/my-angular-app/

      # Step 4: Restart the web server (e.g., Apache or Nginx)
      - name: Restart web server
        run: ssh user@shared-server "sudo systemctl restart nginx"
